const objPostList = [
  {
    id: 1,
    username: 'Timur',
    nickname: '@basyrov',
    timecreate: 1290008882,
    text: 'Сегодня начал разработку сайта на ReactJS',
    img: '',
    repost: 15,
    like: 13,
    save: 22,
  },
  {
    id: 2,
    username: 'Timur',
    nickname: '@basyrov',
    timecreate: 1290008882,
    text: 'Сегодня начал разработку сайта на ReactJS',
    img: '',
    repost: 15,
    like: 13,
    save: 22,
  },
  {
    id: 3,
    username: 'Timur',
    nickname: '@basyrov',
    timecreate: 1290008882,
    text: 'Сегодня начал разработку сайта на ReactJS',
    img: '',
    repost: 15,
    like: 13,
    save: 22,
  },
  {
    id: 4,
    username: 'Дима 5Б класс',
    nickname: '@dima2013',
    timecreate: 129234,
    text: 'Гайд как играть в бравлстар скачать онлайн без смс и регистрации',
    img: '',
    repost: 152,
    like: 413,
    save: 252,
  },
  {
    id: 5,
    username: 'Vasilui',
    nickname: '@Vasya225',
    timecreate: 1290012382,
    text: 'Буст аккаунтов дота 2 до 199 рублей за 5 птс',
    img: '',
    repost: 5555,
    like: 112321,
    save: 1,
  },
];

export default objPostList;
